### ISSUE TITLE
SME review comments

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [solliancenet/MCW-Migrate-Linux-OSS-DB-to-Azure#2]
**MCW SMEs**

Please leave feedback for our authors below.  The more information you can give, the better.  Please note an Exercise and/or Task number so we can quickly find and review.  

If you have no comments, but have completed your review, let us know as well by saying done.

Thank you for all your hard work!

**Comment by DawnmarieDesJardins** [comment]
Student & Trainer guides:
- Can we make this sentence clearer?  I'm not sure what it's saying... 
The workload is also not their most complicated, so it should prove well to prove out the migration plan as it’s developed. 

- PHP web application is mentioned several times.  The acronym isn't spelled out the first time.  Does everyone know what PHP is? (If it's just me, leave as is.)

- Under Pricing, you have two questions with 2 or 3 added "make sure you..." underneath.  Should those be separate questions? Maybe they'd tie in better as bullets underneath the question, thoughts?

**Comment by DawnmarieDesJardins** [comment]
Before the HOL:

- Task 2 is titled Verify On-Premises Web Application.  Is this a proper noun/title?  If not, it should be Verify on-premises web application
- Alt-text titles are copy/pastes of the alt-text.  They should be just titles that show when learners hover over the image.
Example:
The GitHub page with Deploy to Azure button highlighted.](images/before-hol-deploy-to-azure.png "The GitHub page with Deploy to Azure button highlighted.")
Should be more like:
The GitHub page with Deploy to Azure button highlighted.](images/before-hol-deploy-to-azure.png "GitHub page to Azure Portal")

**Comment by DawnmarieDesJardins** [comment]
ReadMe page:
Under Azure services and related products.  Since we're migrating from RedHat and Linux, I think they should listed here too. What about Azure Bastion? (Or is that part of something you already have listed?)

**Comment by DawnmarieDesJardins** [comment]
Step-by-step Lab:

- Check the Alt-text titles to make sure they aren't a copy/paste of the alt-text instead of a title.
- The Abstract and Overview sections are mixed together.  We should put the 3rd paragraph of the Overview into the Abstract.  Remove paragraphs 1 & 3 of the Overview and expand that with more information please.
- Do we need to spell out PHP the first time it's used or does everyone know what that is?
- Under Requirements.  You have an Azure subscription documented in the Before the HOL doc, but the step-by-step says no spending cap for Barracuda.  They should be the same.
- Before the hands-on lab section - please add a hot link to the Before the HOL doc.
- Exercise 1, task 1, #9. - need red box on image.
- Exercise 2, task 2, #1. - need red box on image.
- After the hands-on lab - please add the usual opener about removing resources. (Don't they need to do this to avoid accruing additional charges?)

**Comment by DawnmarieDesJardins** [comment]
Whole MCW:
Approved title for the workshop is **Building the business migration case with Linux and OSS DB to Azure**.  File names, links and doc titles need to be updated to reflect please.

**Comment by DawnmarieDesJardins** [comment]
WDS PPT:
- Update workshop title
- There were some changes I made directly in the guides that need to move over but I can't do them here. (Platform as a Service to Platform-as-a-Service, 3 year service to 3-year service, and front end to front-end)

**Comment by DawnmarieDesJardins** [comment]
@crpietschmann @daneenec 
QC pass all done, thank you!  I'll work on the MS repo tomorrow and send you the link so you can move everything over.  Let me know if anything I put above doesn't make sense.

**Comment by crpietschmann** [comment]
> Student & Trainer guides:
> 
> * Can we make this sentence clearer?  I'm not sure what it's saying...
>   The workload is also not their most complicated, so it should prove well to prove out the migration plan as it’s developed.
> * PHP web application is mentioned several times.  The acronym isn't spelled out the first time.  Does everyone know what PHP is? (If it's just me, leave as is.)
> * Under Pricing, you have two questions with 2 or 3 added "make sure you..." underneath.  Should those be separate questions? Maybe they'd tie in better as bullets underneath the question, thoughts?

PHP is a web app language / framework. So no acronym to spell out.

Under Pricing, the "make sure you..." items are mentioning things to include in the pricing, not so much to specify how to design it in this section. I think it makes sense listed like this as reminders to include, and it's done similarly in other MCWs.

**Comment by crpietschmann** [comment]
@DawnmarieDesJardins @daneenec All QC feedback items have been addressed.

**Comment by DawnmarieDesJardins** [comment]
@crpietschmann 
Thanks Chris!  LOL, I thought the PHP was probably just a me thing. I do try to look things up before I ask my weird questions.  That one sent me down a rabbit hole with PHP, PhP, Php and just confused me more.

Go ahead and move this over to the MS repo and I'll get it published.

As usual, you're amazing. <3

**Comment by crpietschmann** [comment]
> @crpietschmann Thanks Chris! LOL, I thought the PHP was probably just a me thing. I do try to look things up before I ask my weird questions. That one sent me down a rabbit hole with PHP, PhP, Php and just confused me more.
> 
> Go ahead and move this over to the MS repo and I'll get it published.
> 
> As usual, you're amazing. <3

I submitted a PR with this to the MS repo.

https://github.com/microsoft/MCW-Building-the-business-migration-case-with-Linux-and-OSS-DB-to-Azure/pull/1

**Comment by DawnmarieDesJardins** [comment]
We're published!!! Wahoo!  Thank you!
